import { useState, useRef } from 'react';
import {
  FileText, Download, Send, DollarSign, Clock, Calendar, Printer,
  CheckCircle2, AlertCircle, Building2, User, Receipt, IndianRupee
} from 'lucide-react';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from '@/components/ui/dialog';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Separator } from '@/components/ui/separator';
import { useAuth } from '@/contexts/AuthContext';
import { toast } from 'sonner';
import { Invoice } from '@/types/invoice';
import { Timesheet } from '@/types/timesheet';
import { format } from 'date-fns';

const PLATFORM_FEE_PERCENT = 10;

const InvoiceGeneration = () => {
  const { user } = useAuth();
  const [invoices, setInvoices] = useState<Invoice[]>([]);
  const [previewOpen, setPreviewOpen] = useState(false);
  const [selectedInvoice, setSelectedInvoice] = useState<Invoice | null>(null);
  const printRef = useRef<HTMLDivElement>(null);

  // Mock approved timesheets for generating invoices
  const [approvedTimesheets] = useState<Timesheet[]>([
    {
      id: 'ts-demo-1',
      assignmentId: 1,
      freelancerUserId: 101,
      freelancerName: 'Ravi Kumar',
      clientUserId: 201,
      clientName: 'TechCorp Inc.',
      projectTitle: 'React Dashboard Development',
      month: new Date().getMonth() + 1,
      year: new Date().getFullYear(),
      entries: Array.from({ length: 22 }, (_, i) => ({
        date: `${new Date().getFullYear()}-${String(new Date().getMonth() + 1).padStart(2, '0')}-${String(i + 1).padStart(2, '0')}`,
        hours: 8,
      })),
      totalHours: 176,
      status: 'approved',
      submittedOn: new Date().toISOString(),
      reviewedOn: new Date().toISOString(),
    },
  ]);

  const generateInvoice = (ts: Timesheet) => {
    const hourlyRate = 50; // from assignment
    const subtotal = ts.totalHours * hourlyRate;
    const platformFee = subtotal * (PLATFORM_FEE_PERCENT / 100);
    const totalAmount = subtotal + platformFee;
    const invoiceNumber = `INV-${Date.now().toString(36).toUpperCase()}`;

    const dueDate = new Date();
    dueDate.setDate(dueDate.getDate() + 15);

    const invoice: Invoice = {
      id: `inv-${Date.now()}`,
      invoiceNumber,
      assignmentId: ts.assignmentId,
      freelancerUserId: ts.freelancerUserId,
      freelancerName: ts.freelancerName,
      clientUserId: ts.clientUserId,
      clientName: ts.clientName,
      projectTitle: ts.projectTitle,
      timesheetId: ts.id,
      month: ts.month,
      year: ts.year,
      totalHours: ts.totalHours,
      hourlyRate,
      subtotal,
      platformFee,
      platformFeePercent: PLATFORM_FEE_PERCENT,
      totalAmount,
      currency: 'USD',
      currencySymbol: '$',
      status: 'draft',
      paymentStatus: 'pending',
      paidAmount: 0,
      generatedOn: new Date().toISOString(),
      dueDate: dueDate.toISOString(),
    };

    setInvoices(prev => [...prev, invoice]);
    toast.success(`Invoice ${invoiceNumber} generated!`, {
      description: `Total: $${totalAmount.toLocaleString()} (incl. 10% platform fee)`,
    });
  };

  const openPreview = (inv: Invoice) => {
    setSelectedInvoice(inv);
    setPreviewOpen(true);
  };

  const handlePrint = () => {
    const printContent = printRef.current;
    if (!printContent) return;
    const win = window.open('', '_blank');
    if (!win) return;
    win.document.write(`
      <html><head><title>Invoice ${selectedInvoice?.invoiceNumber}</title>
      <style>
        body { font-family: Arial, sans-serif; padding: 40px; color: #333; }
        .header { display: flex; justify-content: space-between; margin-bottom: 30px; }
        .brand { font-size: 24px; font-weight: bold; }
        .brand .orange { color: #f97316; }
        .brand .amber { color: #f59e0b; }
        .brand .blue { color: #2563eb; }
        table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        th, td { padding: 10px 12px; text-align: left; border-bottom: 1px solid #eee; }
        th { background: #f8fafc; font-weight: 600; }
        .total-row { font-weight: bold; font-size: 16px; background: #f0f9ff; }
        .fee-row { color: #6b7280; }
        .info-block { margin-bottom: 20px; }
        .info-block h4 { margin: 0 0 4px; color: #666; font-size: 12px; text-transform: uppercase; }
        .info-block p { margin: 2px 0; }
        .footer { margin-top: 40px; text-align: center; color: #999; font-size: 12px; }
      </style></head><body>
      ${printContent.innerHTML}
      <div class="footer">Generated by ITSupport360 • Platform Fee: 10%</div>
      </body></html>
    `);
    win.document.close();
    win.print();
  };

  const sendInvoice = (inv: Invoice) => {
    setInvoices(prev => prev.map(i => i.id === inv.id ? { ...i, status: 'sent' } : i));
    toast.success('Invoice sent to client!', {
      description: `Invoice ${inv.invoiceNumber} has been emailed to ${inv.clientName}.`,
    });
  };

  const markPaid = (inv: Invoice) => {
    setInvoices(prev => prev.map(i => i.id === inv.id ? { ...i, status: 'paid', paymentStatus: 'completed', paidAmount: i.totalAmount, paidOn: new Date().toISOString() } : i));
    toast.success('Payment recorded!');
  };

  const statusBadge = (status: string) => {
    const map: Record<string, string> = {
      draft: 'bg-slate-500/10 text-slate-400 border-slate-500/20',
      sent: 'bg-blue-500/10 text-blue-400 border-blue-500/20',
      paid: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
      overdue: 'bg-red-500/10 text-red-400 border-red-500/20',
      cancelled: 'bg-slate-500/10 text-slate-500 border-slate-500/20',
    };
    return map[status] || '';
  };

  const uninvoicedTimesheets = approvedTimesheets.filter(
    ts => ts.status === 'approved' && !invoices.some(inv => inv.timesheetId === ts.id)
  );

  return (
    <div className="p-6 space-y-6">
      <div>
        <h2 className="text-lg font-bold text-slate-100 flex items-center gap-2">
          <Receipt className="h-5 w-5 text-cyan-400" /> Invoice Management
        </h2>
        <p className="text-sm text-slate-400 mt-1">Generate invoices from approved timesheets with 10% platform commission</p>
      </div>

      {/* Approved timesheets ready to invoice */}
      {uninvoicedTimesheets.length > 0 && (
        <div className="space-y-3">
          <h3 className="text-sm font-semibold text-emerald-400 uppercase tracking-wider">✅ Ready to Invoice</h3>
          {uninvoicedTimesheets.map(ts => (
            <Card key={ts.id} className="border border-emerald-500/20 bg-[#0D1B2E]">
              <CardContent className="p-4 flex items-center justify-between">
                <div>
                  <p className="font-semibold text-slate-100">{ts.projectTitle}</p>
                  <p className="text-sm text-slate-400">{ts.freelancerName} • {format(new Date(ts.year, ts.month - 1), 'MMMM yyyy')}</p>
                  <p className="text-xs text-slate-500 mt-1">{ts.totalHours}h approved</p>
                </div>
                <Button onClick={() => generateInvoice(ts)} className="gap-1.5 bg-emerald-600 hover:bg-emerald-700">
                  <FileText className="h-4 w-4" /> Generate Invoice
                </Button>
              </CardContent>
            </Card>
          ))}
        </div>
      )}

      {/* Invoice List */}
      {invoices.length > 0 && (
        <div className="space-y-3">
          <h3 className="text-sm font-semibold text-slate-400 uppercase tracking-wider">📄 Invoices ({invoices.length})</h3>
          {invoices.map(inv => (
            <Card key={inv.id} className="border border-slate-700/50 bg-[#0D1B2E] hover:border-slate-600/50 transition-all">
              <CardContent className="p-4">
                <div className="flex items-center justify-between gap-3">
                  <div className="flex items-center gap-3">
                    <div className="h-10 w-10 rounded-lg bg-cyan-500/10 flex items-center justify-center">
                      <FileText className="h-5 w-5 text-cyan-400" />
                    </div>
                    <div>
                      <p className="font-semibold text-slate-100">{inv.invoiceNumber}</p>
                      <p className="text-sm text-slate-400">{inv.projectTitle} • {inv.freelancerName}</p>
                      <p className="text-xs text-slate-500">{format(new Date(inv.year, inv.month - 1), 'MMM yyyy')} • {inv.totalHours}h</p>
                    </div>
                  </div>
                  <div className="flex items-center gap-3">
                    <div className="text-right">
                      <p className="text-lg font-bold text-cyan-400">{inv.currencySymbol}{inv.totalAmount.toLocaleString()}</p>
                      <p className="text-[10px] text-slate-500">Due: {format(new Date(inv.dueDate), 'dd MMM yyyy')}</p>
                    </div>
                    <Badge className={`text-xs ${statusBadge(inv.status)}`}>{inv.status}</Badge>
                  </div>
                </div>
                <Separator className="my-3 bg-slate-700/30" />
                <div className="flex items-center justify-between text-xs text-slate-400">
                  <div className="flex gap-4">
                    <span>Subtotal: {inv.currencySymbol}{inv.subtotal.toLocaleString()}</span>
                    <span className="text-amber-400">Platform Fee (10%): {inv.currencySymbol}{inv.platformFee.toLocaleString()}</span>
                  </div>
                  <div className="flex gap-2">
                    <Button size="sm" variant="outline" onClick={() => openPreview(inv)} className="gap-1 text-xs h-7 border-slate-400 text-white bg-slate-700 hover:bg-slate-600">
                      <FileText className="h-3 w-3 mr-1" /> View
                    </Button>
                    {inv.status === 'draft' && (
                      <Button size="sm" onClick={() => sendInvoice(inv)} className="h-7 text-xs bg-blue-600 hover:bg-blue-700">
                        <Send className="h-3 w-3 mr-1" /> Send
                      </Button>
                    )}
                    {(inv.status === 'sent' || inv.status === 'draft') && inv.paymentStatus !== 'completed' && (
                      <Button size="sm" onClick={() => markPaid(inv)} className="h-7 text-xs bg-emerald-600 hover:bg-emerald-700">
                        <CheckCircle2 className="h-3 w-3 mr-1" /> Mark Paid
                      </Button>
                    )}
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}

      {invoices.length === 0 && uninvoicedTimesheets.length === 0 && (
        <Card className="border border-slate-700/50 bg-[#0D1B2E]">
          <CardContent className="py-16 text-center text-slate-400">
            <Receipt className="h-10 w-10 mx-auto mb-3 opacity-40" />
            <p className="font-medium">No invoices yet</p>
            <p className="text-sm text-slate-500 mt-1">Invoices will be generated from approved timesheets.</p>
          </CardContent>
        </Card>
      )}

      {/* Invoice Preview Dialog */}
      <Dialog open={previewOpen} onOpenChange={setPreviewOpen}>
        <DialogContent className="sm:max-w-2xl bg-white text-gray-900 max-h-[90vh] overflow-auto">
          <DialogHeader>
            <DialogTitle className="text-gray-900">Invoice Preview</DialogTitle>
            <DialogDescription className="text-gray-500">Print or download this invoice</DialogDescription>
          </DialogHeader>

          {selectedInvoice && (
            <div ref={printRef} className="space-y-6 p-4">
              {/* Invoice Header */}
              <div className="flex justify-between items-start">
                <div>
                  <h1 className="text-2xl font-bold">
                    <span className="text-orange-500">IT</span>
                    <span className="text-amber-500">Support</span>
                    <span className="text-blue-600">360</span>
                  </h1>
                  <p className="text-sm text-gray-500 mt-1">Professional IT Staffing Platform</p>
                </div>
                <div className="text-right">
                  <h2 className="text-3xl font-bold text-gray-300">INVOICE</h2>
                  <p className="text-sm font-semibold mt-1">{selectedInvoice.invoiceNumber}</p>
                  <p className="text-xs text-gray-500">Date: {format(new Date(selectedInvoice.generatedOn), 'dd MMM yyyy')}</p>
                  <p className="text-xs text-gray-500">Due: {format(new Date(selectedInvoice.dueDate), 'dd MMM yyyy')}</p>
                </div>
              </div>

              <Separator />

              {/* Bill To / From */}
              <div className="grid grid-cols-2 gap-6">
                <div>
                  <h4 className="text-xs text-gray-500 uppercase font-semibold mb-1">Bill To (Client)</h4>
                  <p className="font-semibold">{selectedInvoice.clientName}</p>
                  <p className="text-sm text-gray-600">Project: {selectedInvoice.projectTitle}</p>
                </div>
                <div>
                  <h4 className="text-xs text-gray-500 uppercase font-semibold mb-1">Service Provider</h4>
                  <p className="font-semibold">{selectedInvoice.freelancerName}</p>
                  <p className="text-sm text-gray-600">Period: {format(new Date(selectedInvoice.year, selectedInvoice.month - 1), 'MMMM yyyy')}</p>
                </div>
              </div>

              {/* Line Items */}
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Description</TableHead>
                    <TableHead className="text-right">Hours</TableHead>
                    <TableHead className="text-right">Rate</TableHead>
                    <TableHead className="text-right">Amount</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  <TableRow>
                    <TableCell>{selectedInvoice.projectTitle} — {format(new Date(selectedInvoice.year, selectedInvoice.month - 1), 'MMM yyyy')}</TableCell>
                    <TableCell className="text-right">{selectedInvoice.totalHours}</TableCell>
                    <TableCell className="text-right">{selectedInvoice.currencySymbol}{selectedInvoice.hourlyRate}/hr</TableCell>
                    <TableCell className="text-right">{selectedInvoice.currencySymbol}{selectedInvoice.subtotal.toLocaleString()}</TableCell>
                  </TableRow>
                  <TableRow className="text-amber-600">
                    <TableCell colSpan={3} className="text-right font-medium">Platform Fee ({selectedInvoice.platformFeePercent}%)</TableCell>
                    <TableCell className="text-right">{selectedInvoice.currencySymbol}{selectedInvoice.platformFee.toLocaleString()}</TableCell>
                  </TableRow>
                  <TableRow className="font-bold text-lg">
                    <TableCell colSpan={3} className="text-right">Total</TableCell>
                    <TableCell className="text-right text-blue-600">{selectedInvoice.currencySymbol}{selectedInvoice.totalAmount.toLocaleString()}</TableCell>
                  </TableRow>
                </TableBody>
              </Table>

              {/* Payment Info */}
              <div className="bg-blue-50 p-4 rounded-lg">
                <p className="text-sm font-semibold text-blue-800">Payment Status: {selectedInvoice.paymentStatus}</p>
                {selectedInvoice.paidAmount > 0 && (
                  <p className="text-sm text-blue-700">Paid: {selectedInvoice.currencySymbol}{selectedInvoice.paidAmount.toLocaleString()}</p>
                )}
                <p className="text-xs text-blue-600 mt-1">Please transfer the amount to the bank details shared separately.</p>
              </div>
            </div>
          )}

          <DialogFooter className="gap-2">
            <Button variant="outline" onClick={() => setPreviewOpen(false)}>Close</Button>
            <Button onClick={handlePrint} className="gap-1.5">
              <Printer className="h-4 w-4" /> Print / Download PDF
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
};

export default InvoiceGeneration;
